In [13]:
# importing all the necessary library
import pandas as pd
import numpy as np

In [14]:
# Reading the dataset into a dataframe alias df
df = pd.read_csv('NEISS2014.csv')

In [15]:
#displaying the result
df.head()

,CPSC Case #,trmt_date,psu,weight,stratum,age,sex,race,race_other,diag,diag_other,body_part,disposition,location,fmv,prod1,prod2,narrative
0,141200216,10/23/14,63,99.704,M,21,Female,None listed,NaN,62,NaN,75,1,1,0,679,1807.0,21YOF LAYING ON THE COUCH AND ROLLED OFF TO TH...
1,140117851,1/4/14,63,81.576,M,62,Female,White,NaN,57,NaN,79,1,1,0,1807,115.0,62YOF TRIPPED OVER THE CORD FOR THE VACUUM CLE...
2,150144993,8/17/14,63,99.704,M,21,Female,None listed,NaN,57,NaN,83,1,0,0,1333,NaN,21YOF FELL OFF A SKATEBOARD AND FRACTURED FOOT
3,150230176,7/27/14,63,99.704,M,30,Female,None listed,NaN,64,NaN,79,1,1,0,4076,NaN,30YOF TRYING TO GET OUT OF BED AND FELT A POP ...
4,141220717,9/8/14,63,99.704,M,16,Male,None listed,NaN,57,NaN,82,1,0,0,1893,NaN,16YOM HAD HAND SLAMMED IN A DOOR FRACTURED HAND

In [16]:
# renaming the column diag to Code to facilitate the joining
df.rename(columns={'diag':'Code'},inplace=True)

In [17]:
df.head()

,CPSC Case #,trmt_date,psu,weight,stratum,age,sex,race,race_other,Code,diag_other,body_part,disposition,location,fmv,prod1,prod2,narrative
0,141200216,10/23/14,63,99.704,M,21,Female,None listed,NaN,62,NaN,75,1,1,0,679,1807.0,21YOF LAYING ON THE COUCH AND ROLLED OFF TO TH...
1,140117851,1/4/14,63,81.576,M,62,Female,White,NaN,57,NaN,79,1,1,0,1807,115.0,62YOF TRIPPED OVER THE CORD FOR THE VACUUM CLE...
2,150144993,8/17/14,63,99.704,M,21,Female,None listed,NaN,57,NaN,83,1,0,0,1333,NaN,21YOF FELL OFF A SKATEBOARD AND FRACTURED FOOT
3,150230176,7/27/14,63,99.704,M,30,Female,None listed,NaN,64,NaN,79,1,1,0,4076,NaN,30YOF TRYING TO GET OUT OF BED AND FELT A POP ...
4,141220717,9/8/14,63,99.704,M,16,Male,None listed,NaN,57,NaN,82,1,0,0,1893,NaN,16YOM HAD HAND SLAMMED IN A DOOR FRACTURED HAND

In [18]:
df_disp = pd.read_csv('DiagnosisCodes.csv')

In [21]:
#merging the dataset with the Diagnosis dataset
df_merge = pd.merge(df,df_disp)

In [22]:
df_merge

,CPSC Case #,trmt_date,psu,weight,stratum,age,sex,race,race_other,Code,diag_other,body_part,disposition,location,fmv,prod1,prod2,narrative,Diagnosis
0,141200216,10/23/14,63,99.7040,M,21,Female,None listed,NaN,62,NaN,75,1,1,0,679,1807.0,21YOF LAYING ON THE COUCH AND ROLLED OFF TO TH...,Internal organ injury
1,140452479,4/18/14,63,81.5760,M,5,Female,White,NaN,62,NaN,75,1,1,0,4076,1870.0,5YOF JUMPING ON THE BED AND STRUCK HEAD ON A M...,Internal organ injury
2,150148600,8/11/14,63,99.7040,M,53,Female,None listed,NaN,62,NaN,75,1,1,0,4074,628.0,53YOF STANDING ON A PLASTIC CHAIR TRYING TO RE...,Internal organ injury
3,150144944,8/17/14,63,99.7040,M,84,Female,None listed,NaN,62,NaN,75,4,0,0,1842,NaN,84YOF FELL DOWN A FLIGHT OF STAIRS AND SUSTAIN...,Internal organ injury
4,141147985,10/4/14,63,99.7040,M,80,Female,None listed,NaN,62,NaN,75,1,5,0,4076,1807.0,80YOF ROLLED OUT OF BED TO THE FLOOR AT THE NU...,Internal organ injury
5,140433503,4/10/14,63,81.5760,M,204,Male,White,NaN,62,NaN,75,1,5,0,1522,NaN,4MOM FELL OUT OF A STROLLER ONTO SIDEWALK ONTO...,Internal organ injury
6,141243987,12/18/14,63,99.7040,M,26,Female,None listed,NaN,62,NaN,75,1,1,0,1843,NaN,26YOF IN A WHEELCHAIR AT HER HOUSE GOING DOWN ...,Internal organ injury
7,141229793,9/4/14,63,99.7040,M,81,Female,None listed,NaN,62,NaN,75,1,1,0,4056,1807.0,81YOF LEANING FORWARD TO PLACE AN ITEM ON A SH...,Internal organ injury
8,150210389,10/31/14,14,50.1602,M,28,Female,White,NaN,62,NaN,75,1,1,0,611,NaN,28YOF SYNCOPAL EPISODE WITH FALL IN SHOWER TH...,Internal organ injury
9,141118664,8/30/14,14,50.1602,M,45,Male,White,NaN,62,NaN,75,1,1,0,1816,NaN,45YOM PT STATES SCAFFOLD CAME APART AT FRIEND...,Internal organ injury
10,140523551,4/4/14,14,41.0402,M,61,Female,White,NaN,62,NaN,75,1,5,0,1842,NaN,61YOF PT BROUGHT IN BY EMS. WAS LEAVING A RE...,Internal organ injury
11,141117201,11/6/14,11,82.3076,S,69,Female,White,NaN,62,NaN,75,1,0,0,1807,NaN,69YOF-HEAD INJURY-GOT DIZZY & FELL HITTING HEA...,Internal organ injury
12,141117200,11/6/14,11,82.3076,S,82,Male,White,NaN,62,NaN,75,1,0,0,1807,NaN,82YOM-HEAD INJURY-FINGER LAC-FELL FROM A WHEEL...,Internal organ injury
13,140921261,9/5/14,81,82.3076,S,55,Male,White,NaN,62,NaN,75,1,0,0,1464,4056.0,55YOM WAS HIT ON HEAD BY *** THAT FELL OFF OF ...,Internal organ injury
14,140532256,5/2/14,90,5.7174,C,3,Male,White,NaN,62,NaN,75,4,1,0,1842,NaN,"3 YOM WAS RUNNING ON STEPS, AT HOME, 2 DAYS AG...",Internal organ injury
15,140513646,4/23/14,90,5.7174,C,7,Male,None listed,NaN,62,NaN,75,1,8,0,604,1650.0,7YOM- YESTERDAY PT WAS @ SCHOOL DROPPED AN ERA...,Internal organ injury
16,140625120,5/27/14,90,5.7174,C,216,Male,None listed,NaN,62,NaN,75,1,5,0,4074,NaN,16MOM- PT WAS CLIMBING ON A CHAIR FELL HITTING...,Internal organ injury
17,140735930,7/13/14,90,5.7174,C,15,Female,White,NaN,62,NaN,75,1,0,0,1333,NaN,15 YOF FELL OFF A LONG BOARD & HIT HEAD- UNHEL...,Internal organ injury
18,140421929,3/30/14,90,5.7174,C,2,Male,White,NaN,62,NaN,75,1,1,0,1555,1807.0,2 YOM WAS HAVING A TEMPER TANTRUM & ROCKED HIS...,Internal organ injury
19,140328352,3/5/14,90,5.7174,C,3,Male,Other / Mixed Race,HISPANIC,62,NaN,75,1,5,0,620,NaN,"3 YOM WAS STANDING ON A STOOL, AT THE AIRPORT,...",Internal organ injury
20,140217479,1/29/14,90,6.6704,C,5,Female,Black/African American,NaN,62,NaN,75,1,1,0,1807,NaN,"5YOF- PT WAS GETTING HAIR COMBED IN PONY TAIL,...",Internal organ injury
21,140341797,3/11/14,90,5.7174,C,8,Female,None listed,NaN,62,NaN,75,1,0,0,661,1807.0,"8 YOF FELL OFF THE TOP BUNK OF BUNK BEDS, HIT...",Internal organ injury
22,140628114,5/31/14,90,5.7174,C,8,Male,Other / Mixed Race,HISPANIC,62,NaN,75,1,1,0,5041,NaN,8 YOM WAS PLAYING BASEBALL IN THE BACK YARD WI...,Internal organ injury
23,140628021,5/28/14,90,5.7174,C,2,Male,Other / Mixed Race,HISPANIC,62,NaN,75,1,1,0,4076,NaN,2 YOM WAS DOING A FLIP ON HIS BED & HIT HEAD O...,Internal organ injury
24,150107432,12/30/14,99,82.3076,S,57,Male,None listed,NaN,62,NaN,75,1,1,0,1842,NaN,57 YOM FELL DOWN 4 STAIRS AT HOME TONIGHT. DX...,Internal organ injury
25,140602253,5/21/14,99,80.0213,S,6,Female,White,NaN,62,NaN,75,1,0,0,1244,NaN,6YOF FELL FROM MONKEY BARS ONTO FACE/ HEAD INJ...,Internal organ injury
26,140251542,2/20/14,99,80.0213,S,6,Male,White,NaN,62,NaN,75,1,8,0,1726,NaN,6YOM GOT PUSHED INTO LOCKER AT SCHOOL/ HEAD IN...,Internal organ injury
27,140665284,6/27/14,99,82.3076,S,85,Female,White,NaN,62,NaN,75,1,1,0,676,1884.0,"85YOF TRIPPED ON CARPET, STRUCK HEAD ON WALL/ ...",Internal organ injury
28,140602328,5/27/14,99,80.0213,S,12,Male,White,NaN,62,NaN,75,1,1,0,550,NaN,12 YOM STRUCK IN HEAD WITH CELL PHONE BY SISTE...,Internal organ injury
29,140461095,4/23/14,99,80.0213,S,48,Male,White,NaN,62,NaN,75,1,1,0,893,NaN,"48YOM CUTTING BRANCHES ON TREE, STRUCK ON HEAD...",Internal organ injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65469,140341439,3/17/14,50,74.3851,L,22,Female,None listed,NaN,47,NaN,92,1,4,0,1647,NaN,^22 YOF DEVELOPED FROSTBITE TO RT. FINGERTIPS ...,"Burns, not specified"
65470,140460909,4/25/14,85,80.0213,S,26,Female,White,NaN,47,NaN,83,1,9,0,3299,1615.0,26YOF SWOLLEN FEET AFTER HIKING 5 MILES WEARIN...,"Burns, not specified"
65471,140626840,6/6/14,22,14.3089,V,63,Female,White,NaN,47,NaN,83,1,9,0,3223,1615.0,PT WAS FISHING WITH OPEN TOE SHOES ON AND FOOT...,"Burns, not specified"
65472,140161690,1/23/14,68,81.5760,M,15,Male,White,NaN,47,NaN,93,1,5,0,1615,NaN,15YOM FROSTBITE TO TOE WALKED 3 MILES HOME FRO...,"Burns, not specified"
65473,141143544,11/16/14,18,5.7174,C,8,Male,Black/African American,NaN,47,NaN,83,1,0,0,1211,NaN,"8 YOM PLAYING FOOTBALL OUTSIDE, GOT IN CAR SAY...","Burns, not specified"
65474,140714407,6/28/14,18,5.7174,C,2,Female,Black/African American,NaN,46,NaN,92,1,0,0,4061,NaN,2 YOF ELECTRICAL BURN AFTER PLAYING WITH OUTLE...,"Burns, electrical"
65475,141051959,2/24/14,32,5.7174,C,222,Male,White,NaN,46,NaN,92,1,1,0,1533,NaN,22MOM STUCK HIS FINGER IN SOCKET OF NIGHTLIGHT...,"Burns, electrical"
65476,140132564,1/9/14,22,14.3089,V,53,Male,White,NaN,46,NaN,92,1,1,0,348,NaN,"GRABBED AN ELECTRIC HEATER. 2ND DEGREE BURN, F...","Burns, electrical"
65477,140719165,7/5/14,58,15.6716,V,42,Female,None listed,NaN,46,NaN,82,1,1,0,4071,4061.0,42 YOF WENT TO PLUG IN LAMP INTO ELECTRICAL SO...,"Burns, electrical"
65478,150100613,12/26/14,85,82.3076,S,28,Male,White,NaN,46,NaN,82,1,0,0,573,NaN,28YOM HAD 120 VOLT AC ELECTRICAL SHOCK ABOUT 1...,"Burns, electrical"
65479,140404768,3/29/14,18,5.7174,C,2,Male,Black/African American,NaN,46,NaN,82,1,1,0,1682,4061.0,2 YOM STUCK A BOBBY PIN INTO A WALL OUTLET. D...,"Burns, electrical"
65480,140430372,4/8/14,35,14.3089,V,79,Female,White,NaN,46,NaN,36,1,5,0,4061,NaN,79 YOF BURNED LOWER LEG ON ELECTRICAL OUTLET A...,"Burns, electrical"
65481,141002156,9/26/14,17,15.6716,V,30,Female,None listed,NaN,46,NaN,82,1,1,0,4071,NaN,30YOF ELEC BURN HAND PLUGGING IN LAMP,"Burns, electrical"
65482,140506794,4/22/14,30,81.5760,M,7,Female,White,NaN,46,NaN,82,1,0,0,4041,NaN,7YOF BURNED HAND WHILE TRYING TO TURN ON OLD L...,"Burns, electrical"
65483,140748189,7/14/14,62,87.2960,S,49,Female,White,NaN,46,NaN,31,1,1,0,1602,NaN,49 YO WF BLOWING DRYING HAIR HAS ELECTRICAL SH...,"Burns, electrical"
65484,140255852,2/25/14,21,14.3089,V,16,Male,None listed,NaN,46,NaN,92,1,1,0,557,4061.0,16YM PLUGGING IN ***&FELT SHOCK NOW WITH THUMB...,"Burns, electrical"
65485,141003908,9/26/14,65,82.3076,S,12,Male,White,NaN,46,NaN,82,1,8,0,4074,NaN,12YOM WITH ELECTRICAL BURN TO HAND AFTER LEANI...,"Burns, electrical"
65486,140734320,7/10/14,68,99.7040,M,11,Male,White,NaN,46,NaN,83,1,1,0,685,NaN,11YOM BURN TO BOTTOM OF FOOT STEPPED ON AN ELE...,"Burns, electrical"
65487,140961701,9/22/14,90,5.7174,C,3,Female,Asian,NaN,46,NaN,92,1,1,0,1682,4061.0,3 YOF STUCK HAIR PIIN IN ELECTRICAL OUTLET & ...,"Burns, electrical"
65488,140754841,7/25/14,29,87.2960,S,24,Female,Black/African American,NaN,46,NaN,83,1,1,0,4081,NaN,"24YOF AT HOME, BURNED HER LEG ON AN ELECTRICAL...","Burns, electrical"
65489,140835590,8/15/14,20,5.7174,C,6,Male,White,NaN,46,NaN,82,1,8,0,4071,NaN,6YOM STUCK FINGER IN LAMP SOCKET WITHOUT BULB ...,"Burns, electrical"
65490,140750517,7/18/14,17,15.6716,V,3,Female,None listed,NaN,46,NaN,82,1,1,0,1682,4061.0,3YOF ELEC BURN HAND- PUT BOBBY PIN IN ELECTRIC...,"Burns, electrical"
65491,140215942,2/6/14,85,80.0213,S,2,Female,White,NaN,46,NaN,92,1,1,0,4081,NaN,2YOF GOT SHOCKED FROM ELECTRICAL CORD NOW HAS ...,"Burns, electrical"
65492,140858417,8/16/14,68,99.7040,M,52,Male,White,NaN,46,NaN,82,1,0,0,4062,NaN,52YOM 2ND DEGREE ELECTRICAL BURNS TO HANDS HEL...,"Burns, electrical"
65493,140514972,4/29/14,64,14.3089,V,4,Female,Black/African American,NaN,46,NaN,82,1,0,0,4081,NaN,4YOF PRESENTS WITH BURNS TO HAND. PT PICKED UP...,"Burns, electrical"
65494,140607827,5/31/14,78,81.5760,M,16,Male,Black/African American,NaN,46,NaN,92,1,1,0,277,NaN,"16 YOM INJURED FINGER,PLUGGING IN IRON,PLUG SP...","Burns, electrical"
65495,140127991,1/10/14,18,6.6704,C,3,Female,Black/African American,NaN,46,NaN,92,1,0,0,1682,4061.0,3 YOF STUCK A BOBBY PIN INTO AN ELECTRICAL SOC...,"Burns, electrical"
65496,140307067,2/13/14,44,74.3851,L,15,Male,White,NaN,46,NaN,77,1,0,0,388,4061.0,"15 YOM REMOVING HEATER FROM WALL OUTLET, FORGO...","Burns, electrical"
65497,141223676,12/3/14,16,99.7040,M,221,Male,White,NaN,46,NaN,82,1,1,3,4081,1884.0,21 MONTH OLD MALE WAS PLAYING WITH CORD PLUGGE...,"Burns, electrical"
65498,140752126,7/19/14,22,15.6716,V,213,Female,White,NaN,46,NaN,92,1,1,0,1533,4061.0,PT BURNED FINGER PLAYING WITH A NIGHT LIGHT TH...,"Burns, electrical"

In [23]:
#disposition code 4 and 2 are of interest so filtered rows which satisfies any of the condition
df_filter = df_merge[(df_merge['disposition'] == 4) | (df_merge['disposition'] == 2)]

In [24]:
df_filter.shape

(4630, 19)

In [25]:
#count the injures frequencies on the above dataset
df_filter['Diagnosis'].value_counts()

Fracture                                       2078
Internal organ injury                           731
Other/Not Stated                                676
Contusions, Abrasions                           246
Laceration                                      226
Poisoning                                       106
Ingested foreign object                          74
Concussions                                      74
Burns, thermal (from flames or hot surface)      56
Strain or Sprain                                 54
Dislocation                                      51
Burns, scald (from hot liquids or steam)         49
Hematoma                                         43
Amputation                                       32
Submersion (including Drowning)                  23
Nerve damage                                     19
Foreign body                                     18
Anoxia                                           16
Avulsion                                         16
Puncture                                         15
Aspirated foreign object                          7
Hemorrhage                                        5
Dental injury                                     4
Electric shock                                    3
Crushing                                          3
Dermatitis, Conjunctivitis                        2
Burns, not specified                              2
Burns, chemical (caustics, etc.)                  1
Name: Diagnosis, dtype: int64

In [27]:
# I have also included the diag_other column in my analysis
df_filter['diag_other'].value_counts()

PAIN                    235
CHEST PAIN               59
SYNCOPE                  41
CELLULITIS               31
NS                       22
BACK PAIN                11
RHABDOMYOLYSIS           11
HIP PAIN                 10
NOT STATED                7
SEIZURE                   6
TRAUMA                    6
SYNCOPE AND COLLAPSE      6
SOB                       4
ABD PAIN                  4
CVA                       4
ABSCESS                   4
SWELLING                  4
KNEE PAIN                 3
LOW BACK PAIN             3
KNEE INJURY               3
CARDIAC ARREST            3
DYSPNEA                   3
HYPHEMA                   3
WEAKNESS                  3
AMS                       3
HERNIATED DISC            3
LEG INJURY                3
DEHYDRATION               3
PNEUMONIA                 2
ASTHMA EXACERBATION       2
                       ...
DEGLOVING                 1
TISSUE NECROSIS           1
RESPIRATORY ARREST        1
STATUS ASTHMATICUS        1
HEAD INJURY               1
PENIS INJURY              1
ARM INJURY                1
PRESEPTAL CELLULITIS      1
GIB                       1
DIZZY/WEAKNESS            1
HYPOVOLEMIC SHOCK         1
ACS                       1
PNEUMOMEDIASTINUM         1
FOLLICULITIS              1
MI                        1
MUSCULOSKELETAL PAIN      1
RT KNEE INJURY            1
COPD                      1
LOSS OF CONCIOUSNESS      1
BROWN-SYNDROME            1
OTITIS EXTERNA            1
DISC HERNIATION           1
UROSEPSIS                 1
BACK PX                   1
L LOWER EXT WEAKNESS      1
KNEE WOUND DEHISCENC      1
ATERIAL OCCLUSION         1
LOW BACK P AIN            1
NO INJURY                 1
BILAT FOOT PAIN           1
Name: diag_other, Length: 187, dtype: int64

In [28]:
# records with disposition column 6 are filtered out for my analysis
df_filter_2 = df_merge[(df_merge['disposition'] == 6)]

In [29]:
df_filter_2.shape

(619, 19)

In [36]:
#frequncies are captured to get into the result
df_filter_2['Code'].value_counts()

71    257
59    123
62     63
53     52
68     24
64     21
58     12
56     10
51     10
63      7
52      7
57      6
48      5
60      4
65      3
55      3
49      2
42      2
74      2
50      2
72      2
73      1
41      1
Name: Code, dtype: int64

In [33]:
df_filter_2['diag_other'].value_counts()

PAIN                    123
BACK PAIN                10
NO DIAGNOSIS              9
KNEE PAIN                 5
INJURY                    4
N/S                       4
FOOT PAIN                 3
LOWER BACK PAIN           3
SHOULDER PAIN             3
NECK PAIN                 3
RT FOOT PAIN              2
LOW BACK PAIN             2
FINGER INJURY             2
EYE IRRITATION            2
HEADACHE                  2
EYE PAIN                  2
LWBS                      1
SWELLING                  1
NUMBNESS                  1
LT ELBOW PAIN             1
NO INJURIES               1
BODY CRAMPS               1
PAIN, SWELLING            1
RT THUMB PAIN             1
ASTHMA EXACERBATION       1
NOSE INJURY-LBFE          1
ANKLE PAIN                1
SUBC. HEMORRHAGE          1
NOT SEEN BY MD            1
EYE INJ                   1
                       ...
PAIN TO NECK              1
COSTOCHONDRITIS           1
OTITIS MEDIA              1
WRIST PAIN                1
WASP STING                1
R ARM PAIN & RASH         1
OAUB                      1
ANIMAL BITE               1
PRESSURE UNDER CAST       1
ABDOMINAL PAIN. LWBS      1
HERNIATED DISC            1
TOE INJ                   1
NON-SPECIFIC INJURY       1
ABD PAIN                  1
L LEG PAIN                1
SHOULDER INJURY           1
HYPOTHERMIA               1
INJURY L FOREARM          1
BLISTER                   1
FOOT INJURY               1
HERNIA                    1
SOB                       1
NEAR SYCOPE               1
ANKLE INJURY              1
BURNING SENSATION         1
KNEE INJURY               1
SWOLLEN NOSE              1
ABDOMINAL PAIN            1
SYNCOPE                   1
LOWER BACK R SIDE         1
Name: diag_other, Length: 93, dtype: int64